# Generated by Django 5.0.6 on 2024-05-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
